### ISSUE TITLE
Online PoodLL Submissions are lost in the course/activity restoration process

### ISSUE THREAD

**Issue by gaudreaj** [justinhunt/moodle-assign_submission_onlinepoodll#1]
Hi there,

It seems Online PoodLL submissions are lost in the course/activity restoration process. 
Here are the steps to reproduce : 
- Create 2 new courses with both 1 teacher and 1 student enrolled (They must be the same users in both courses).
- As the teacher in course 1, create an assignment with submission type "Online PoodLL"
- As the student, Record and submit the assignment
- As an administrator, create a backup of course 1 with user data 
- Restore course 1 in course 2 (use "Delete the contents of the existing course and then restore")
- _You can see that the student submission is no longer there_

I checked the PoodLL feedback plugin, and everything works fine there! 
Also, the tests were made with Moodle 2.5.

Great plugin by the way! Very useful to us!

Jean-Philippe

**Comment by justinhunt** [comment]
OK thanks. I will look at that over the next week, and hopefully can reproduce, nail it.

**Comment by gaudreaj** [comment]
Great! Thanks a lot!

**Comment by justinhunt** [comment]
Sorry it took a little longer than that, but it should be fixed now.

**Comment by gaudreaj** [comment]
No problems, it was not that urgent! Thanks again anyway! I'll try testing the fix by the end of the week
