### ISSUE TITLE
Cannot save assignments - You must not attach more than 1 files here

### ISSUE THREAD

**Issue by ghost** [justinhunt/moodle-assign_submission_onlinepoodll#7]
Hi, some teachers have reported a strange bug where they cannot save an assignment in Moodle. This bug seemed to appear randomly after editing some h5p content. It affects only one teacher. Other teachers can save the same assignment. Here is a forum which discuss the bug in more details.
https://moodle.org/mod/forum/discuss.php?d=424457

After much investigation, I was able to reproduce it and debug to see what was going on. What I found was that the plugin assignsubmission_onlinepoodll has a filemanager type element called "backimage". When saving an assignment which has no backimage such as a new assignment for example and when the "Online Poodll" submission type is not selected, the backimage element is hidden and it is assigned a null default value. Then, when Moodle comes to validate the form it checks the number of draft files assigned to this element VS the maximum number of authorized files which is 1 in this case. The DB request checks in the mdl_files table in search for the draft files which it thinks are associated with this element based on the user context (which is why it affects only one user) and the itemid which it takes from the value of the filemanager element. Since our value is null (0) then all draft files from this particular user with an itemid = 0 are considered as backimages then the error message appear and the assignment cannot be saved. We have to select the "Online Poodll" submission type to see the message since the backimage element is hidden.

My understanding is that the "backimage" element should be assigned a value given by the Moodle function file_get_unused_draft_itemid() which is how the toHtml() function of the filemanager element use to
assign an id to the element when it is rendered. That explains why the bug only happens when the backimage element is hidden. This value would then be used by Moodle to look for the right draft file with
itemid = element value.

Also the reason why this bug was going away on its own is that Moodle periodically delete old draft files in a cron job.

**Error preventing the save of the assignment**
![assignsubmission_onlinepoodll error message](https://github.com/justinhunt/moodle-assign_submission_onlinepoodll/assets/41542508/d40420bb-52f1-4bdb-8ca6-03b2c21a16b8)

**Some draft files with itemid 0 created by core_h5p for the user context**
![core_h5p draft files](https://github.com/justinhunt/moodle-assign_submission_onlinepoodll/assets/41542508/144a34eb-0465-49c1-a888-4db23051bf9f)

**Moodle filemanager element maxfiles validation. It looks for all draft files in the current user context with itemid = $element->getValue()**
![Moodle filemanager maxfiles check](https://github.com/justinhunt/moodle-assign_submission_onlinepoodll/assets/41542508/12f724b5-5b06-450e-b3fc-34510492d863)

**OnlinePoodll get_settings function set the default value for backimage element to $backimage which is null if no entry exists in the mdl_assign_plugin_config for this assignement and onlinepoodll plugin. The element value is then 0.**
![assignsubmission_onlinepoodll backimage](https://github.com/justinhunt/moodle-assign_submission_onlinepoodll/assets/41542508/9879d4cf-fe2e-4ce1-a682-d15ae010bad2)

I tried to insert this code in locallib.php line 107 just under $backimage = $this->get_config('backimage'); to see if it would fix the bug and it does. But I'm not sure if its the way to do it...
`if(empty($backimage)) {
    require_once("$CFG->libdir/filelib.php");
    $backimage = file_get_unused_draft_itemid();
}`

**Comment by justinhunt** [comment]
Thanks for doing all the work to track that down. I understand your explanation and what it must have taken to get to that point.  Your suggestion might be the right way to do this. 

Its a long time since I worked with that code and its not very fresh in my mind. But I do recall having to mess around getting the form to save with files selected, and without files selected. If it does both of those things using your suggestion, and also saves reliably even when the submission type is not being used, then I think we could use it.

I will look at this as soon as I can, but it is likely to be next week at the earliest

**Comment by ghost** [comment]
Thanks for your quick reply Justin !

**Comment by magdesm** [comment]
Hello! Is there any update with this issue ? it seems we encountered the same problem on our moodle.

Thank you

**Comment by justinhunt** [comment]
I am really sorry for the delay in this. I didn't get back to it as I had intended. @ghost analysis was spot on. This was really old code and was written when the moodle file system just came out.

The fix is here:
https://github.com/justinhunt/moodle-assign_submission_onlinepoodll/commit/cc9760a8d37fc67bba17f6fe89d55008862de651

And I will release it from now on Moodle.org

**Comment by magdesm** [comment]
Thank you Justin!
